### ISSUE TITLE
Inability to invoke "aniso" setting

### ISSUE THREAD

**Issue by lnnbig** [ICAMS/calphy#122]
calphy version: 1.3.7
pylammpsmpi version: 0.2.13

Even after specifying "iso: [False]" in the input file, the pressure remains consistently adjusted isotropically, as indicated by the "Pressure adjusted in iso" entry in the output log files. Below is a brief review of the input file "input.yaml" and the output file "calphy.log". Full versions of these files are also included as attachments. 
[file.tar.gz](https://github.com/ICAMS/calphy/files/14721818/file.tar.gz)

**_(calphy) xx/xx$ cat input.yaml_**

element: ["O","Si"]
mass: [15.999,28.085]

calculations:
- mode: ts
  temperature: [300,1500]
  pressure: [[500000]]
  lattice: [conf.data]
  **iso: [False]**
  reference_phase: solid
  pair_style: pace
  pair_coeff: '* * SiOx_potential.yace O Si'
  timestep: 0.001
  spring_constants: [2,4]
  n_equilibration_steps: 1000
  n_switching_steps: [1000,1000]
  n_iterations: 1
  equilibration_control: nose-hoover

nose_hoover:
  thermostat_damping: 0.1
  barostat_damping: 0.1

tolerance:
  solid_fraction: 0

queue:
  cores: 12

**_(calphy) xx/xx$ cat ts-conf.data-solid-300-500000/calphy.log_**

2024-03-22 12:12:24,471 calphy.helpers INFO     Temperature start: 300.000000 K, temperature stop: 1500.000000 K, pressure: 500000.000000 bar
2024-03-22 12:12:24,471 calphy.helpers INFO     **Pressure adjusted in iso**
2024-03-22 12:12:24,471 calphy.helpers INFO     Reference phase is solid
2024-03-22 12:12:24,471 calphy.helpers INFO     Equilibration stage is done using nose-hoover barostat/thermostat
2024-03-22 12:12:24,471 calphy.helpers INFO     Nose-Hoover thermostat damping is 0.100000
2024-03-22 12:12:24,471 calphy.helpers INFO     Nose-Hoover barostat damping is 0.100000
2024-03-22 12:12:24,471 calphy.helpers INFO     These values can be tuned by adding in the input file:
2024-03-22 12:12:24,471 calphy.helpers INFO     nose_hoover:
2024-03-22 12:12:24,471 calphy.helpers INFO        thermostat_damping: <float>
2024-03-22 12:12:24,471 calphy.helpers INFO        barostat_damping: <float>
2024-03-22 12:12:24,471 calphy.helpers INFO     Integration stage is done using Nose-Hoover thermostat and barostat when needed
2024-03-22 12:12:24,471 calphy.helpers INFO     Thermostat damping is 0.100000
2024-03-22 12:12:24,471 calphy.helpers INFO     Barostat damping is 0.100000
2024-03-22 12:12:24,471 calphy.helpers INFO     576 atoms in 1 cells on 12 cores
2024-03-22 12:12:24,471 calphy.helpers INFO     pair_style: pace
2024-03-22 12:12:24,471 calphy.helpers INFO     pair_coeff: * * xx/xx/SiOx_potential.yace O Si

**Comment by srmnitc** [comment]
@lnnbig the iso keyword has now been removed, and its automatically set through the pressure input. See [here](https://calphy.org/en/latest/inputfile.html#pressure). In this case, specifying pressure as `pressure: [[500000, 500000, 500000]]` should fix the issue.

**Comment by srmnitc** [comment]
I am going to go ahead and close the issue, feel free to open again if this does not resolve the issue. Thanks again for reporting!

**Comment by lnnbig** [comment]
> @lnnbig the iso keyword has now been removed, and its automatically set through the pressure input. See [here](https://calphy.org/en/latest/inputfile.html#pressure). In this case, specifying pressure as `pressure: [[500000, 500000, 500000]]` should fix the issue.

Thank you for your suggestion. However, a new error has arisen. Please see below.

(calphy) xx/xx$ calphy -i input.yaml
/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py:657: UserWarning: Old style input file calphy < v2 found. Converted input in new.input.yaml. Please check!
  warnings.warn(f'Old style input file calphy < v2 found. Converted input in {outfile}. Please check!')
Traceback (most recent call last):
  File "/home/liang/deepmd-kit3.0.0/envs/calphy/bin/calphy", line 33, in <module>
    sys.exit(load_entry_point('calphy==1.3.7', 'console_scripts', 'calphy')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/kernel.py", line 165, in main
    run_jobs(args["input"])
  File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/kernel.py", line 55, in run_jobs
    calculations = read_inputfile(inputfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py", line 551, in read_inputfile
    calculations = _read_inputfile(outfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py", line 561, in _read_inputfile
    calculations.append(Calculation(**calc))
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Main input class
pressure.float
  Input should be a valid number [type=float_type, input_value=[500000.0, 500000.0, 500000.0], input_type=list]
    For further information visit https://errors.pydantic.dev/2.6/v/float_type
pressure.list[float]
  List should have at most 2 items after validation, not 3 [type=too_long, input_value=[500000.0, 500000.0, 500000.0], input_type=list]
    For further information visit https://errors.pydantic.dev/2.6/v/too_long
pressure.list[list[float]]
  List should have at most 2 items after validation, not 3 [type=too_long, input_value=[500000.0, 500000.0, 500000.0], input_type=list]
    For further information visit https://errors.pydantic.dev/2.6/v/too_long

**Comment by lnnbig** [comment]
@lnnbig<https://github.com/lnnbig> the iso keyword has now been removed, and its automatically set through the pressure input. See here<https://calphy.org/en/latest/inputfile.html#pressure>. In this case, specifying pressure as pressure: [[500000, 500000, 500000]] should fix the issue.

Thank you for your suggestion. However, a new error has arisen. Please see below.


(calphy) xx/xx$ calphy -i input.yaml
/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py:657: UserWarning: Old style input file calphy < v2 found. Converted input in new.input.yaml. Please check!
warnings.warn(f'Old style input file calphy < v2 found. Converted input in {outfile}. Please check!')
Traceback (most recent call last):
File "/home/liang/deepmd-kit3.0.0/envs/calphy/bin/calphy", line 33, in
sys.exit(load_entry_point('calphy==1.3.7', 'console_scripts', 'calphy')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/kernel.py", line 165, in main
run_jobs(args["input"])
File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/kernel.py", line 55, in run_jobs
calculations = read_inputfile(inputfile)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py", line 551, in read_inputfile
calculations = _read_inputfile(outfile)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py", line 561, in _read_inputfile
calculations.append(Calculation(**calc))
^^^^^^^^^^^^^^^^^^^
File "/home/liang/deepmd-kit3.0.0/envs/calphy/lib/python3.11/site-packages/pydantic/main.py", line 171, in init
self.pydantic_validator.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Main input class
pressure.float
Input should be a valid number [type=float_type, input_value=[500000.0, 500000.0, 500000.0], input_type=list]
For further information visit https://errors.pydantic.dev/2.6/v/float_type
pressure.list[float]
List should have at most 2 items after validation, not 3 [type=too_long, input_value=[500000.0, 500000.0, 500000.0], input_type=list]
For further information visit https://errors.pydantic.dev/2.6/v/too_long
pressure.list[list[float]]
List should have at most 2 items after validation, not 3 [type=too_long, input_value=[500000.0, 500000.0, 500000.0], input_type=list]
For further information visit https://errors.pydantic.dev/2.6/v/too_long



________________________________

**Comment by srmnitc** [comment]
Looks like there is double brackets in the input. It should be `[[x,x,x]]` and not `[x,x,x]`, could you please check this again, or post your input file, thanks!

**Comment by srmnitc** [comment]
Ah I see there is issue #123 , closing this again.
