### ISSUE TITLE
Run ZrCu and get error message

### ISSUE THREAD

**Issue by ZAhra-Rjz** [ICAMS/calphy#125]
Hi,
In order to get familiar with calphy I tried to run the example file in the calphy package for ZrCu. when I run the input file, I got this error:

Traceback (most recent call last):
  File "/home/zar/.conda/envs/calphy/bin/calphy", line 33, in <module>
    sys.exit(load_entry_point('calphy==1.3.7', 'console_scripts', 'calphy')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zar/.conda/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/kernel.py", line 165, in main
    run_jobs(args["input"])
  File "/home/zar/.conda/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/kernel.py", line 55, in run_jobs
    calculations = read_inputfile(inputfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zar/.conda/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py", line 548, in read_inputfile
    outfile = _convert_legacy_inputfile(file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zar/.conda/envs/calphy/lib/python3.11/site-packages/calphy-1.3.7-py3.11.egg/calphy/input.py", line 603, in _convert_legacy_inputfile
    reference_phase = np.atleast_1d(ci['reference_phase'])
                                    ~~^^^^^^^^^^^^^^^^^^^
KeyError: 'reference_phase'

and this is the input script:
element: ['Zr', 'Cu']
mass: [91.224, 63.546]
calculations:
- mode: ts 
  temperature: [300, 900]
  pressure: [0]
  lattice: [/home/calphy/examples/ZrCu_EAM_test/ZrCu/ZrCu.data]
  state: [solid]
  nsims: 1

md:
  pair_style: eam/fs
  pair_coeff: "* * /home/calphy/examples/ZrCu_EAM_test/ZrCu/ZrCu.eam.fs Zr Cu"
  timestep: 0.001
  tdamp: 0.1
  pdamp: 0.1
  te: 25000
  ts: 50000
  
queue:
  scheduler: local
  cores: 4
  commands:
    - source ~/.zghrc
    - conda activate py3

Can you tell me what is the problem?
Thank you

**Comment by srmnitc** [comment]
@ZAhra-Rjz Thanks! Unfortunately the example you are running is an outdated one. Please try one from [here](https://github.com/ICAMS/calphy/tree/main/examples) prefixed with `example_01` to `example_12`
