### ISSUE TITLE
UnpicklingError when using MTP

### ISSUE THREAD

**Issue by Leimeroth** [ICAMS/calphy#47]
Using my pr #46 it is possible to use MTPs with calphy without errors obviously related to the parsing of user specified input. However, there still seems to be a problem with the  sub process output that is rather mysterious to me.
All calphy calculations I tried now produce a complete log.lammps without any errors and a calphy.log without errors, but ending with the line:
2022-10-13 12:42:16,565 calphy.helpers INFO     pair_coeff: * *

The error traceback:
```
Traceback (most recent call last):
  File "/nfshome/leimeroth/.local/bin/calphy_kernel", line 33, in <module>
    sys.exit(load_entry_point('calphy==1.2.2', 'console_scripts', 'calphy_kernel')())
  File "/nfshome/leimeroth/git_projects/calphy_gpu/calphy/queuekernel.py", line 148, in main
    _ = routine_fe(job)
  File "/nfshome/leimeroth/git_projects/calphy_gpu/calphy/routines.py", line 341, in routine_fe
    job.run_averaging()
  File "/nfshome/leimeroth/git_projects/calphy_gpu/calphy/solid.py", line 160, in run_averaging
    self.run_zero_pressure_equilibration(lmp)
  File "/nfshome/leimeroth/git_projects/calphy_gpu/calphy/phase.py", line 362, in run_zero_pressure_equilibration
    lmp.command("run              %d"%int(self.calc.md.n_small_steps))
  File "/nfshome/leimeroth/git_projects/pylammpsmpi/pylammpsmpi/lammps_wrapper.py", line 72, in func_wrapper
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
    fut = func(*args, **kwargs)
  File "/nfshome/leimeroth/git_projects/pylammpsmpi/pylammpsmpi/utils/lammps.py", line 536, in command
    _ = self._receive()
  File "/nfshome/leimeroth/git_projects/pylammpsmpi/pylammpsmpi/utils/lammps.py", line 83, in _receive
    output = pickle.load(self._process.stdout)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

I am not sure whether this is a calphy bug, a pylammpsmpi bug or some problem with the lammps/mtp interface,  since it is not an officially supported package of lammps.

**Comment by srmnitc** [comment]
@Leimeroth I am also not sure the origin of this issue, could you maybe please try a simple script; something along the lines of [this](https://github.com/pyiron/pylammpsmpi/blob/master/tests/in.simple) and run it through `pylammpsmpi`? That way, we could see if it is from calphy side.

**Comment by Leimeroth** [comment]
If i run a slightly modified version of that input file:

```
# 3d Lennard-Jones melt

units           metal
atom_style      atomic
atom_modify     map array

lattice         fcc 3.63
region          box block 0 4 0 4 0 4
create_box      1 box
create_atoms    1 box
mass            1 63.0

velocity        all create 1.44 87287 loop geom

pair_style      mlip pyiron_default_mlip.ini
pair_coeff      * *

neighbor        0.3 bin
neigh_modify    delay 0 every 1 check yes

compute         1 all temp
compute         2 all pressure 1
compute         ke all ke/atom
compute         msd all msd
compute         v all property/atom vx vy vz

variable        fx atom fx
variable        tt equal temp
variable        test string "25"
fix                        1 all nve
fix              2 all ave/time 10 1 10 c_1 c_2



run             10
```
using a very simple script

```
import os
from pylammpsmpi import LammpsLibrary

exe_path = os.path.dirname(os.path.abspath(__file__))
citation_file = os.path.join(exe_path, "citations.txt")

lammps_file = os.path.join(exe_path, "in.simple")
lmp = LammpsLibrary(cores=2, mode='local', cmdargs=["-cite", citation_file])
lmp.file(lammps_file)
```
Everything works fine as far as I can tell. A lammps log is written and no errors are thrown.
Should I test something specific regarding the output f.e.?

**Comment by srmnitc** [comment]
@Leimeroth could you please try this? This way it should try to get the output of each command. 

```
from pylammpsmpi import LammpsLibrary

lmp = LammpsLibrary(cores=2, mode='local')

lmp.command("units           metal")
lmp.command("atom_style      atomic")
lmp.command("atom_modify     map array")

lmp.command("lattice         fcc 3.63")
lmp.command("region          box block 0 4 0 4 0 4")
lmp.command("create_box      1 box")
lmp.command("create_atoms    1 box")
lmp.command("mass            1 63.0")

lmp.command("velocity        all create 1.44 87287 loop geom")

lmp.command("pair_style      mlip pyiron_default_mlip.ini")
lmp.command("pair_coeff      * *")
lmp.command("run                0")
```

**Comment by Leimeroth** [comment]
This script runs without any problems

**Comment by srmnitc** [comment]
@pmrv and I are planning to sit down for a working MTP integration sometime early November. Once we know when I can let you know and you could join through Zoom if you are interested.

**Comment by srmnitc** [comment]
MTP potentials now works with calphy.
