### ISSUE TITLE
reset_timestep() got an unexpected keyword argument 'init_commands'

### ISSUE THREAD

**Issue by antonf-ekb** [ICAMS/calphy#71]
Dear Calphy developers!
I tried to run examples 8 and 9, but got the following output:
`Traceback (most recent call last):
  File "/home/u0050/.local/bin/calphy_kernel", line 33, in <module>
    sys.exit(load_entry_point('calphy==1.2.8', 'console_scripts', 'calphy_kernel')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/queuekernel.py", line 150, in main
    _ = routine_ts(job)
        ^^^^^^^^^^^^^^^
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/routines.py", line 360, in routine_ts
    routine_fe(job)
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/routines.py", line 341, in routine_fe
    job.run_averaging()
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/solid.py", line 188, in run_averaging
    self.process_traj("traj.equilibration_stage2.dat", "conf.equilibration.data")
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/phase.py", line 580, in process_traj
    ph.reset_timestep(conf, os.path.join(self.simfolder, "current.data"), init_commands=self.calc.md.init_commands)
TypeError: reset_timestep() got an unexpected keyword argument 'init_commands'`

At the same time, the Calphy tests run OK. I use pylammpsmpi  0.1.0 and its own test also run OK. LAMMPS version is  lammps-2022.12.22, which is installed separately from Calphy but the python wrapper has been created and tested. 

Thank you in advance for help,
Anton.

**Comment by antonf-ekb** [comment]
Hi, I'm not sure this belongs to the same issue, but know when I try to run ZrCu EAM example, I got the following error 
`Traceback (most recent call last):
  File "/home/u0050/.local/bin/calphy", line 33, in <module>
    sys.exit(load_entry_point('calphy==1.2.8', 'console_scripts', 'calphy')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/kernel.py", line 113, in main
    run_jobs(args["input"])
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/kernel.py", line 55, in run_jobs
    calculations = read_inputfile(inputfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u0050/.local/lib/python3.11/site-packages/calphy-1.2.8-py3.11.egg/calphy/input.py", line 773, in read_inputfile
    reference_phase = Calculation.convert_to_list(ci["reference_phase"])
                                                  ~~^^^^^^^^^^^^^^^^^^^
KeyError: 'reference_phase'
`

**Comment by srmnitc** [comment]
Is it this one: https://github.com/ICAMS/calphy/tree/main/examples/ZrCu_EAM, I am really sorry, only the folders with `example_` are updated ones. I should remove the old ones. You can see a CuZr example [here](https://github.com/ICAMS/calphy/tree/main/examples/example_10).

**Comment by antonf-ekb** [comment]
Yes, I meant exactly this example. I've tried example_10, but now it seems like some LAMMPS-related error:
`ERROR: Cannot use fix press/berendsen with triclinic box (src/fix_press_berendsen.cpp:268)`
Do some particular styles have to be installed to run this example?

**Comment by srmnitc** [comment]
It should not need to be, ok I will check this and reopen this issue.

**Comment by srmnitc** [comment]
Fixed in #85
