### ISSUE TITLE
Calphy example_01 errors

### ISSUE THREAD

**Issue by iainbest** [ICAMS/calphy#79]
Hi - before testing some calphy calculations using ACE potentials, I attempted to run the examples using the simpler/faster EAM for Fe and Cu. The calphy tests all run without errors.

For example_01, with calphy release 1.2.10, I run 

`~/calphy/examples/example_01$ calphy -i input.yaml`

which proceeds to find the single calculation, but returns no report.yaml file since it errors. Within the fe-BCC-100-0.sub.err file we have:

`Traceback (most recent call last):
  File "/home/u2082383/.local/bin/calphy_kernel", line 33, in <module>
    sys.exit(load_entry_point('calphy==1.2.10', 'console_scripts', 'calphy_kernel')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2082383/.local/lib/python3.11/site-packages/calphy-1.2.10-py3.11.egg/calphy/queuekernel.py", line 148, in main
    _ = routine_fe(job)
        ^^^^^^^^^^^^^^^
  File "/home/u2082383/.local/lib/python3.11/site-packages/calphy-1.2.10-py3.11.egg/calphy/routines.py", line 341, in routine_fe
    job.run_averaging()
  File "/home/u2082383/.local/lib/python3.11/site-packages/calphy-1.2.10-py3.11.egg/calphy/solid.py", line 167, in run_averaging
    self.run_pressure_convergence(lmp)
  File "/home/u2082383/.local/lib/python3.11/site-packages/calphy-1.2.10-py3.11.egg/calphy/phase.py", line 500, in run_pressure_convergence
    raise ValueError("Pressure did not converge after MD runs, maybe change lattice_constant and try?")
ValueError: Pressure did not converge after MD runs, maybe change lattice_constant and try?`

Similar errors occur for other example_0x, although some calculations within other examples proceed as expected. 

Any advice would be appreciated. Thanks in advance,
Iain

**Comment by srmnitc** [comment]
@iainbest  This was due to the Berendsen thermostat and barostat being used as default. The input files have been fixed now, and it should work.
