### ISSUE TITLE
KeyError: 'element'

### ISSUE THREAD

**Issue by gswylq** [ICAMS/calphy#87]
Dear every,
I have install the calphy soft, but when I run the example I get the following error. I hope you give some suggests. 
Thank you.
Q. Li

error:
Traceback (most recent call last):
  File "/home/gswylq/miniconda3/envs/calphy/bin/calphy", line 8, in <module>
    sys.exit(main())
  File "/home/gswylq/miniconda3/envs/calphy/lib/python3.8/site-packages/calphy/kernel.py", line 113, in main
    run_jobs(args["input"])
  File "/home/gswylq/miniconda3/envs/calphy/lib/python3.8/site-packages/calphy/kernel.py", line 55, in run_jobs
    calculations = read_inputfile(inputfile)
  File "/home/gswylq/miniconda3/envs/calphy/lib/python3.8/site-packages/calphy/input.py", line 795, in read_inputfile
    calc = Calculation.generate(indata)
  File "/home/gswylq/miniconda3/envs/calphy/lib/python3.8/site-packages/calphy/input.py", line 707, in generate
    calc.element = indata["element"]
KeyError: 'element'

**Comment by srmnitc** [comment]
@gswylq could you please show your input file?

**Comment by gswylq** [comment]
> @gswylq could you please show your input file?
Thank you for your help.
[input.yaml.txt](https://github.com/ICAMS/calphy/files/13064888/input.yaml.txt)

**Comment by srmnitc** [comment]
This is due to the input file being in the new format, while the conda package is not yet updated (I assume you installed from conda). One option would be to install the package from the repository directly. Otherwise you could also wait for the new conda release which would be available in the next few days.

**Comment by gswylq** [comment]
This problem has been solved based on the answer above

**Comment by bsnow31** [comment]
Has the conda release been updated to fix this issue? I just installed with conda and got this same error.

**Comment by srmnitc** [comment]
> Has the conda release been updated to fix this issue? I just installed with conda and got this same error.

Turns ouyt it wasnt, it will be updated once [this](https://github.com/conda-forge/calphy-feedstock/pull/25) pull request is merged.
